# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d0a63ad9d7ece800ec7742470e1cc701b66fe22ef9b08e3c2c88f344e1793c7e9d349ff8b340b487b9906b0e5be01b4f22d9766f348fede4c57becb47c9516d

test:
  secret_key_base: e073409d38eb858f36189d7f7704b560f96449be43b8a82b6c5ab00c883e2f146c4155d4971c762be9b8a3030ca7379ce444d445b98b17bb072dd57a8917450e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
